Repository EC-CUBE/ProductReview-plugin, pull requests merged in 2022-08, with the labels that each got.

#65 ★の数の計算に、非公開のレビューを含まないようにする。公開されているレビューのみで★の計算をするようにする。
  Repository/ProductReviewRepository.php
Labels: enhancement

#79 レビュー管理ページのbootstrap5対応
  Resource/template/admin/index.twig
Labels: bug, bugbounty2022:pr:entry

#81 Cannot modify header informationエラーを修正
  Controller/Admin/ProductReviewController.php
Labels: bug, bugbounty2022:pr:entry

#88 チェックボックスの位置を修正
  Resource/template/admin/edit.twig
Labels: bugbounty2022:pr:entry, bugbounty2022:pr:recognition

#86 適切なマークアップ
  Resource/template/default/review.twig
Labels: bugbounty2022:pr:entry, bugbounty2022:pr:recognition

#83 bootstrap5対応漏れ
  Resource/template/admin/edit.twig
Labels: bugbounty2022:pr:entry, bugbounty2022:pr:recognition
